# Generated by Django 5.0.6 on 2024-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='', max_length=255),
        ),
    ]
