# Generated by Django 5.0.6 on 2024-06-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_content_en_article_title_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content_en',
            new_name='content_trad',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title_en',
            new_name='title_trad',
        ),
    ]
